# Generated by Django 5.2.6 on 2025-10-07 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_next', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='messagelog',
            options={},
        ),
        migrations.AddField(
            model_name='chat',
            name='bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='platform',
            field=models.CharField(choices=[('slack', 'Slack'), ('telegram', 'Telegram'), ('discord', 'Discord')], default='telegram', max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chat',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_next.chat'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
